.\" -*-nroff-*-
.\"
.\" mpop version 1.0.11
.\"
.\" Copyright (C) 2005, 2006, 2007  Martin Lambers
.\"
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.2 or
.\" any later version published by the Free Software Foundation; with no
.\" Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.TH MPOP 1 2007-08
.SH NAME
mpop \- A POP3 client 
.SH SYNOPSIS
.IP "Mail retrieval mode (default):"
.B mpop 
[option...] [--] [account...]
.br
.B mpop
--host=host [option...]
.IP "Server information mode:"
.B mpop 
[option...] --serverinfo [account...]
.br
.B mpop 
--host=host [option...] --serverinfo
.SH DESCRIPTION
In mail retrieval mode of operation, mpop retrieves mails from one or more POP3
mailboxes, optionally does some filtering, and delivers them through a mail
delivery agent (MDA) or to maildir folders or mbox files. Mails that were
successfully delivered before will not be retrieved a second time, even if
errors occur or mpop is terminated in the middle of a session.
.br
In server information mode, mpop prints information about one or more POP3
servers.
.br
If no account names are given on the command line, the one named \fIdefault\fP
will be used. 
.SH EXIT STATUS
The standard sendmail exit codes are used, as defined in sysexits.h.
.SH OPTIONS
Options override configuration file settings, for every used account.
.IP "\fBGeneral Options\fP"
.RS
.IP "--version"
Print version information. This includes information about the library used for
TLS/SSL support (if any), the library used for authentication, and the
authentication mechanisms supported by this library.
.IP "--help"
Print help.
.IP "-P, --pretend"
Print the configuration settings that would be used, but do not take further
action.  An asterisk ('*') will be printed instead of your password.
.IP "-d, --debug"
Print lots of debugging information, including the whole conversation with the
POP3 server. Be careful with this option: the (potentially dangerous) output 
will not be sanitized, and your password may get printed in an easily decodable
format!
.br
This option implies --half-quiet, because the progress output would interfere
with the debugging output.
.RE
.IP "\fBChanging the mode of operation\fP"
.RS
.IP "-S, --serverinfo"
Print information about the POP3 server(s) and exit. This includes information
about supported features (pipelining, authentication methods, TOP command, ...),
about parameters (time for which mails will not be deleted, minimum time
between logins, ...), and about the TLS certificate (if TLS is active).
.RE
.IP "\fBConfiguration options\fP"
.RS
.IP "-C, --file=\fIconffile\fP"
Use the given file instead of ~/.mpoprc as configuration file.
.IP "--host=\fIhostname\fP"
Use this POP3 server with settings from the command line; do not use any
configuration file data. You cannot use both this option and account names on
the command line.
.IP "--port=\fInumber\fP"
Set the port number to connect to. See the
.BR port
command below.
.IP "--timeout=(\fIoff\fP|\fIseconds\fP)"
Set a network timeout. See the \fBtimeout\fP command below.
.IP "--pipelining=(\fIauto\fP|\fIon\fP|\fIoff)"
Enable or disable POP3 pipelining. See the \fBpipelining\fP command below.
.IP "--auth[=(\fIon\fP|\fImethod\fP)]"
Set the authentication method to automatic (with "on") or manually choose an
authentication method. See the \fBauth\fP command below.
.IP "--user=[\fIusername\fP]"
Set or unset the user name for authentication. See the \fBuser\fP command
below.
.IP "--tls[=(\fIon\fP|\fIoff\fP)]"
Enable or disable TLS/SSL encryption. See the \fBtls\fP command below.
.IP "--tls-starttls[=(\fIon\fP|\fIoff\fP)]"
Enable or disable the POP3 STLS command for TLS encryption. See the
\fBtls_starttls\fP command below.
.IP "--tls-trust-file=[\fIfile\fP]"
Set or unset a trust file for TLS encryption. See the \fBtls_trust_file\fP
command below.
.IP "--tls-key-file=[\fIfile\fP]"
Set or unset a key file for TLS encryption. See the \fBtls_key_file\fP command
below.
.IP "--tls-cert-file=[\fIfile\fP]"
Set or unset a cert file for TLS encryption. See the \fBtls_cert_file\fP
command below.
.IP "--tls-certcheck[=(\fIon\fP|\fIoff\fP)]"
Enable or disable server certificate checks for TLS encryption. See the
\fBtls_certcheck\fP command below.
.IP "--tls-force-sslv3[=(\fIon\fP|\fIoff\fP)]"
Force TLS/SSL version SSLv3. See the \fBtls_force_sslv3\fP command below.
.RE
.IP "\fBOptions specific to mail retrieval mode\fP"
.RS
.IP "-q, --quiet"
Do not print status or progress information.
.IP "-Q, --half-quiet"
Print status but not progress information.
.IP "-a, --all-accounts"
Query all accounts in the configuration file.
.IP "-A, --auth-only"
Authenticate only; do not retrieve mail. Useful for SMTP-after-POP.
.IP "-s, --status-only"
Print number and size of mails in each account only; do not retrieve mail.
.IP "-n, --only-new[=(\fIon\fP|\fIoff\fP)]"
Process only new messages. See the \fBonly_new\fP command below.
.IP "-k, --keep[=(\fIon\fP|\fIoff\fP)]"
Do not delete mails from POP3 servers, regardless of other options or settings.
See the \fBkeep\fP command below.
.IP "--killsize=(\fIoff\fP|\fIsize\fP)"
Set or unset kill size. See the \fBkillsize\fP command below.
.IP "--skipsize=(\fIoff\fP|\fIsize\fP)"
Set or unset skip size. See the \fBskipsize\fP command below.
.IP "--filter=[\fIprogram\fP]"
Set a filter which will decide whether to retrieve, skip, or delete each mail
by investigating the mail's headers. See the \fBfilter\fP command below.
.IP "--delivery=\fImethod\fP,\fImethod_arguments...\fP"
How to deliver messages received from this account. See the \fBdelivery\fP 
command below. Note that a comma is used instead of a blank to separate the 
method from its arguments.
.IP "--uidls-file=\fIfilename\fP"
File to store UIDLs in. See the \fBuidls_file\fP command below.
.RE
.SH USAGE
mpop normally uses a configuration file (~/.mpoprc by default) that
contains information about your POP3 accounts.
.PP
Skip to the EXAMPLES section for a quick start.
.PP
The configuration file is a simple text file.  Empty lines and comment lines
(whose first non-blank character is '#') are ignored.
The file must have no more permissions than user read/write.
.br
Every other line must contain a command and may contain an argument to that
command.
.br
The argument may be enclosed in double quotes ("), for example if its first or
last character is a blank.
.br 
If the first character of a filename is the tilde (~), this tilde will be
replaced by $HOME.
.br
If a command accepts the argument \fIon\fP, it also accepts an empty argument
and treats that as if it was \fIon\fP.
.PP
Commands are as follows:
.IP "defaults"
Set defaults. The following configuration commands will set default values for
all following account definitions.
.IP "account \fIname\fP [:\fIaccount\fP[,...]]"
Start a new account definition with the given name. The current default values
are filled in.
.br
If a colon and a list of previously defined accounts is given after the account
name, the new account, with the filled in default values, will inherit all 
settings from the accounts in the list.
.IP "host \fIhostname\fP"
The POP3 server to retrieve mails from.
The argument may be a host name or a network address.
Every account definition must contain this command.
.IP "port \fInumber\fP"
The port that the POP3 server listens on. The default is 110, unless TLS
without STARTTLS is used, in which case it is 995.
.IP "timeout (\fIoff\fP|\fIseconds\fP)"
Set or unset a network timeout, in seconds. The default is 180 seconds. The 
argument \fIoff\fP means that no timeout will be set, which means that the
operating system default will be used.
.IP "pipelining (\fIauto\fP|\fIon\fP|\fIoff\fP)"
Enable or disable POP3 pipelining. The default is \fIauto\fP, which means that
mpop enables pipelining for POP3 servers that advertize this capability, and 
disables it for all other servers. See also --serverinfo.
.br
It is always safe to disable pipelining. It is not recommended to force
pipelining for servers that are not known to support it.
.br 
Pipelining works by sending up to \fIPIPELINE_MAX\fP commands to the server, 
then begin to read its answers, and refill the command pipeline when the number
of unanswered commands drops to \fIPIPELINE_MIN\fP. PIPELINE_MIN and 
PIPELINE_MAX are compile time contants.
.IP "delivery \fImethod\fP \fImethod_arguments...\fP
How to deliver messages received from this account.
.RS
.IP "delivery mda \fIcommand\fP"
Deliver the mails through a mail delivery agent (MDA).
.br
All occurences of %F in the command will be replaced with the envelope from
address of the current message (or MAILER-DAEMON if none is found). Note that
this address is guaranteed to contain only letters a-z and A-Z, digits 0-9, and
any of ".@_-+/", even though that is only a subset of what is theoretically
allowed in a mail address. Other characters, including those interpreted by the
shell, are replaced with "_".  Nevertheless, you should put %F into single
quotes: '%F'.
.br
Use "delivery mda /usr/bin/procmail -f '%F' -d $USER" for the procmail MDA.
.br
Use "delivery mda /usr/sbin/sendmail -oi -oem -f '%F' -- $USER" to let your MTA
handle the mail.
.br
Use "delivery mda /usr/local/bin/msmtp --host=localhost --from='%F' -- 
$USER@`hostname`.`dnsdomainname`" to pass the mail to your MTA via SMTP. 
(This is what fetchmail does by default.)
.IP "delivery maildir \fIdirectory\fP"
Deliver the mails to the given maildir directory. The directory must exist and 
it must be a valid maildir directory; mpop will not create directories.
.IP "delivery mbox \fImbox-file\fP"
Deliver the mails to the given file in mbox format. The file will be locked 
with \fBfcntl(2)\fP. mpop uses the MBOXRD mbox format variant; see the
documentation of the mbox format.
.PP
If the delivery method needs to parse the mail headers for an envelope from 
address (the mda method if the command contains %F, and the mbox method), then
it needs to create a temporary file to store the mail headers (but not the body)
in. See $TMPDIR in the FILES / ENVIRONMENT section.
.RE
.IP "uidls_file \fIfilename\fP"
The file to store UIDLs in. These are needed to identify new messages.
%U in the filename will be replaced by the username of the current account.
%H in the filename will be replaced by the hostname of the current account.
If the filename contains directories that do not exist, mpop will create them.
mpop locks this file for exclusive access when accessing the associated POP3 
account.
.br
The default value is "~/.mpop_uidls/%U_at_%H". You can also use a single UIDLS
file for multiple accounts, but then you cannot poll more than one of these
accounts at the same time.
.IP "auth [(\fIon\fP|\fImethod\fP)]"
This command chooses the POP3 authentication method. With the argument
\fIon\fP, mpop will choose the best one available for you (see below). This
is the default.
.br
You probably need to set a username (with \fBuser\fP) and password (with
\fBpassword\fP). 
If no password is set but one is needed during authentication, mpop will try to
find it in ~/.netrc, and if that fails, mpop will prompt you for it.
.br
Available methods are \fIuser\fP, \fIapop\fP, \fIplain\fP, \fIlogin\fP,
\fIcram-md5\fP, \fIdigest-md5\fP, \fIgssapi\fP, \fIexternal\fP, \fIlogin\fP,
and \fIntlm\fP.
Note that one or more of these methods may be unavailable due to lack of
support in the underlying authentication library. Use the \fB--version\fP
option to find out which methods are supported.
.br
The \fIuser\fP, \fIplain\fP and \fIlogin\fP methods send your authentication
data in cleartext over the net, and the \fIapop\fP and \fIntlm\fP methods are 
vulnerable to attacks. These methods should therefore only be used together with
the \fBtls\fP command.
.br
If you don't choose the method yourself, mpop chooses the best secure method
that the POP3 server supports. Secure means that your authentication data will
not be sent in cleartext over the net. For TLS encrypted connections, every
authentication method is secure in this sense. If TLS is not active, only
gssapi, digest-md5, and cram-md5 ntlm are secure in this sense.
.br
The \fIexternal\fP is special: the actual authentication happens outside of the
SMTP protocol, typically by sending a TLS client certificate (see the
\fBtls_cert_file\fP command). The \fIexternal\fP method merely confirms that
this authentication succeeded for the given user (or, if no user name is given,
confirms that authentication succeeded). This authentication method is not
chosen automatically; you have to request it manually.
.IP "user \fIlogin\fP"
Set your user name for POP3 authentication.
.IP "password \fIsecret\fP"
Set your password for POP3 authentication.
If no password is set but one is needed during authentication, mpop will try to
find it in ~/.netrc, and if that fails, mpop will prompt you for it.
.IP "ntlmdomain [\fIdomain\fP]"
Set a domain for the \fBntlm\fP authentication method. The default is to use no
domain (equivalent to an empty argument), but some servers seem to require one,
even if it is an arbitrary string.
.br
.IP "tls [(\fIon\fP|\fIoff\fP)]"
This command enables or disables TLS (also known as SSL) encrypted connections
to the POP3 server. Not every server supports this, and many that support it 
require the additional command \fBtls_starttls off\fP. 
.br
With TLS/SSL, the connection with the POP3 server will be protected against
eavesdroppers and man-in-the-middle attacks. To use TLS/SSL, it is required to 
either use the \fBtls_trust_file\fP command (highly recommended) or to disable 
\fBtls_certcheck\fP.
.IP "tls_starttls [(\fIon\fP|\fIoff\fP)]"
This command chooses the TLS/SSL variant: with STARTTLS (\fIon\fP, default) or 
POP3-over-TLS (\fIoff\fP). Most servers support the latter variant, which is 
also commonly referred to as "POP3 with SSL".
.IP "tls_trust_file \fIfile\fP"
This command activates strict server certificate verification.
.br
The filename must be the absolute path name of a file in PEM format containing
one or more certificates of trusted Certification Authorities (CAs).
.br
On Debian based systems, you can install the \fBca-certificates\fP package and
use the file \fB/etc/ssl/certs/ca-certificates.crt\fP.
.br
An empty argument disables this feature.
.IP "tls_key_file \fIfile\fP"
This command (together with the \fBtls_cert_file\fP command) enables mpop to
send a client certificate to the POP3 server if requested.
.br
The filename must be the absolute path name of a file in PEM format containing
a private key. Be sure that this file is only readable by yourself!
.br
An empty argument disables this feature.
.IP "tls_cert_file \fIfile\fP"
This command (together with the \fBtls_key_file\fP command) enables mpop to
send a client certificate to the POP3 server if requested.
.br
The filename must be the absolute path name of a file in PEM format containing
a certificate.
.br
An empty argument disables this feature.
.IP "tls_certcheck [(\fIon\fP|\fIoff\fP)]"
This command enables or disables checks for the server certificate.
.br
\fBWARNING\fP: When the checks are disabled, TLS/SSL sessions will be vulnerable
to man-in-the-middle attacks!
.IP "tls_force_sslv3 [(\fIon\fP|\fIoff\fP)]"
Force TLS/SSL version SSLv3. This might be needed to use SSL with some old and
broken servers. Do not use this unless you have to.
.IP "only_new [(\fIon\fP|\fIoff\fP)]"
By default, mpop processes only new messages (new messages are those that were
not already successfully retrieved in an earlier session). If this option is 
turned off, mpop will process all messages.
.IP "keep [(\fIon\fP|\fIoff\fP)]"
Keep all mails on the POP3 server, never delete them. The default behaviour is
to delete mails that have been successfully retrieved or filtered by kill
filters.
.IP "killsize (\fIoff\fP|\fIsize\fP)"
Mails larger than the given size will be deleted (unless the \fBkeep\fP command
is used, in which case they will just be skipped).
.br
The size argument must be zero or greater. If it is followed by a 'k' or 
an 'm', the size is measured in kilobytes/megabytes instead of bytes.
.br
Note that some POP3 servers report slightly incorrect sizes for mails; see
\fBNOTES\fP below. 
.IP "skipsize (\fIoff\fP|\fIsize\fP)"
Mails larger than the given size will be skipped (not downloaded).
.br
The size argument must be zero or greater. If it is followed by a 'k' or 
an 'm', the size is measured in kilobytes/megabytes instead of bytes.
.br
Note that some POP3 servers report slightly incorrect sizes for mails; see
\fBNOTES\fP below. 
.IP "filter [\fIcommand\fP]"
Set a filter which will decide whether to retrieve, skip, or delete each mail
by investigating the mail's headers. The POP3 server must support the POP3 TOP
command for this to work; see option \fB--serverinfo\fP above. An empty argument
disables filtering.
.br
All occurences of %F in the command will be replaced with the envelope from 
address of the current message (or MAILER-DAEMON if none is found).
Note that this address is guaranteed to contain only letters a-z and A-Z,
digits 0-9, and any of ".@_-+/", even though that is only a subset of what is
theoretically allowed in a mail address. Other characters, including those
interpreted by the shell, are replaced with "_". Nevertheless, you should put
%F into single quotes: '%F'.
.br
All occurences of %S in the command will be replaced with the size of the 
current mail as reported by the POP3 server.
.br
The mail headers (plus the blank line separating the headers from the body)
will be piped to the command. Based on the return code, mpop decides
what to do with the mail:
.br
0: proceed normally; no special action
.br
1: delete the mail; do not retrieve it
.br
2: skip the mail; do not retrieve it
.br
Return codes greater than or equal to 3 mean that an error occured. The
sysexits.h error codes may be used to give information about the kind of the
error, but this is not necessary.
.RE
.SH FILTERING
There are three filtering commands available.  They will be executed in the
following order:
.br
.B killsize
.br
.B skipsize
.br
.B filter
.br
If a filtering command applies to a mail, the remaining filters will not be
executed.
.SH EXAMPLES
.B Configuration file
.PP
# Default values for all accounts.
.br
defaults
.br
# Activate TLS.
.br
tls on
.br
# Enable full TLS certificate checks.
.br
tls_trust_file /etc/ssl/certs/ca-certificates.crt
.br
# Use the POP3-over-TLS variant instead of the STARTTLS variant.
.br
# This is often called "POP3 with SSL". Most servers support this.
.br
tls_starttls off
.br
# Use the procmail mail delivery agent.
.br
delivery mda "/usr/bin/procmail -f '%F' -d $USER"
.br
# For Sendmail:
.br
#delivery mda "/usr/sbin/sendmail -oi -oem -f '%F' -- $USER"
.br
# For msmtp (delivery via SMTP):
.br
#delivery mda "/usr/bin/msmtp --host=localhost --from='%F' -- $USER"
.br
# Delivery to a maildir folder:
.br
#delivery maildir ~/Mail/incoming
.br
# Delivery to a MBOX mail folder:
.br
#delivery mbox ~/Mail/new
.br

.br
# Two pop3 mailboxes at the provider.
.br
account provider1
.br
host mx.provider.example
.br
user john_smith
.br
password secret
.br
# Copy the settings from the previous account, and only override the
.br
# settings that differ.
.br
account provider2 : provider1
.br
user joey
.br
password secret2
.br

.br
# A freemail service.
.br
account freemail
.br
host pop.freemail.example
.br
user 1238476
.br
password pass
.br

.br
# Set a default account (optional).
.br
account default : provider1
.br

.br
.PP
.B Manually finding the right CA certificate for \fBtls_trust_file\fP
.PP
The following example works as of 2007-04-18.
.br
For the Gmail POP server, you first issue the following command:
.br
.B mpop --serverinfo --host=pop.gmail.com --tls=on --tls-starttls=off 
.B   --tls-certcheck=off
.br
The option \fI--tls-starttls=off\fP is needed for Gmail, but may not be 
necessary for other servers. The option \fI--tls-certcheck=off\fP allows
mpop to accept any certificate, so that it can print some information about it.
.br
According to the output of this command, the issuer of the server certificate 
is "Equifax Secure Certificate Authority". This means that you have to trust the
Equifax CA to use full TLS security. You can download the appropriate
certificate from http://www.geotrust.com/resources/root_certificates/index.asp 
(Equifax was bought by GeoTrust). The file you need for the \fBtls_trust_file\fP
command is \fIEquifax_Secure_Certificate_Authority.cer\fP.
.br
The following command should now succeed:
.br
.B mpop --serverinfo --host=pop.gmail.com --tls=on --tls-starttls=off
.B  --tls-trust-file=Equifax_Secure_Certificate_Authority.cer
.br

.br
.PP
.B Filtering with SpamAssassin
.PP
The command
.B filter\ "/path/to/spamc -c > /dev/null"
will delete all mails that SpamAssassin thinks are spam. Since no message body
is passed to SpamAssassin, you should disable all body-specific tests in the 
SpamAssassin configuration file; for example set
.B use_bayes 0.
.PP
If your mail provider runs SpamAssassin for you, you just have to check for the
result. The following script can do that when used as an mpop filter:
.br
#!/bin/sh
.br
if [ "`grep "^X-Spam-Status: Yes"`" ]; then
.br
    exit 1  # kill this message
.br
else
.br
    exit 0  # proceed normally
.br
fi
.br
Since the filter command is passed to a shell, you can also use this directly:
.br
.B filter if [\ "`grep\ "^X-Spam-Status: Yes"`" ]; then exit 1; else exit 0; fi
.SH FILES / ENVIRONMENT
.IP "~/.mpoprc"
Default configuration file.
.IP "~/.mpop_uidls"
Default directory to store UIDLs files in.
.IP "~/.netrc"
The .netrc file contains login information. If a password is not found in the
configuration file, msmtp will search it in .netrc before prompting the user for
it. The syntax of .netrc is described in 
.BR netrc (5)
or 
.BR ftp (1).
.IP "$USER, $LOGNAME"
These variables override the user's login name. $LOGNAME is only used if $USER
is unset. The user's login name is used for Received headers.
.IP "$TMPDIR"
Directory to create temporary files in. If this is unset, a system specific
default directory is used.
.SH NOTES
Some POP3 servers still do not support the UIDL command. In this case, mpop 
cannot recognize messages that were already successfully retrieved, and will
treat all messages as new. Use the \fB--serverinfo\fP option to find out if a 
server supports the UIDL command.
.br
Some POP3 servers count end-of-line characters as two bytes (CRLF) instead 
of one (LF), so that the size of a mail as reported by the POP3 server is 
slightly larger than the actual size. This has the following consequences:
The size filters are not accurate. Do not rely on exact size filtering.
The progress output may display inaccurate (slightly too low) percentage values
for the first mail retrieved from a POP3 server.  mpop will detect this after
the first mail has been read and will display corrected values for subsequent
mails.
.SH AUTHOR
mpop was written by Martin Lambers <marlam@marlam.de>
.br
Other authors are listed in the AUTHORS file in the source distribution.
.SH SEE ALSO
.BR procmail (1),
.BR spamassassin (1),
.BR fetchmail (1),
.BR getmail (1),
.BR netrc (5)
or
.BR ftp (1),
.BR mbox (5),
.BR fcntl (2)
